package mission_dat


const( 
	LEVEL_BOX_AWARD_COUNT = 2
	MAX_LEVEL_BOX_AWARD_COUNT = 3
	RANDDOM_BOX_AWARD_COUNT = 1
	LEVEL_PHYSICAL_MIN = 3
	LEVEL_HARD_PHYSICAL_MIN = 1
	LEVEL_BOX_AWARD_NIL = -1
	LEVEL_BOX_AWARD_COIN = 0
	LEVEL_BOX_AWARD_ITEM = 1
	LEVEL_BOX_AWARD_EQUIMENT = 2
	LEVEL_BOX_AWARD_EXP = 3
	LEVEL_BOX_AWARD_MULTIPLE_EXP = 4
	LEVEL_BOX_AWARD_MULTIPLE_COIN = 5
	LEVEL_BOX_AWARD_PET_BALL = 6
)
const( 
	EXTEND_LEVEL_TYPE_RESOURCE = 1
	EXTEND_LEVEL_TYPE_BUDDY = 9
	EXTEND_LEVEL_TYPE_PET = 10
	EXTEND_LEVEL_TYPE_GHOST = 11
)
const( 
	RESOURCE_COIN_LEVEL = 1
	RESOURCE_EXP_LEVEL = 2
	EXTEND_LEVEL_PET_MAX_ROUND_NUM = 30
	EXTEND_LEVEL_PASS_CD_TIME = 600
	EXTEND_LEVEL_BUDDY_MAX_DAILY_NUM = 5
	EXTEND_LEVEL_RESOURCE_MAX_DAILY_NUM = 2
	EXTEND_LEVEL_PET_MAX_DAILY_NUM = 5
	EXTEND_LEVEL_GHOST_MAX_DAILY_NUM = 5
)
const( 
	ONE_STAR = 1
	TWO_STAR = 2
	THREE_STAR = 3
)
const( 
	LEVEL_TYPE_MISSION = 0
	LEVEL_TYPE_HARD = 8
	LEVEL_TYPE_DESPAIR = 19
)
const( 
	NORMAL = 0
	ELITE = 1
	BOSS = 2
	ITEM_PET_BALL = 250
	ITEM_PET_BALL_RATE = 50
)
const( 
	FREE_RELIVE_LEVEL = 20
	FIRST_RELIVE_INGOT = 10
)
const( 
	RECOVER_BATTLE_PET = 1
	RECOVER_MEMBERS_HELATH = 2
	RECOVER_SKILL_RELEASE = 3
)
const( 
	PVE_LEVEL_DAILY_NUM = 1
	PVE_LEVEL_INIT_ENEMY_GROUP_NUM = 2
	PVE_LEVEL_MAX_ROUND = 15
)
const( 
	HARD_LEVEL_BUY_INGOT = 50
	HARD_LEVEL_MAX_BUY_TIME = 1
)
const( 
	CHEST_TYPE_COPPER = 1
	CHEST_TYPE_SILVER = 2
	CHEST_TYPE_GOLD = 3
)


var ExtendLevelCoinOpenDay = []int{1,2,3,4,5,6,0,}

var ExtendLevelExpOpenDay = []int{1,2,3,4,5,6,0,}

var ExtendLevelBuddyOpenDay = []int{3,6,0,}

var ExtendLevelPetOpenDay = []int{2,5,0,}

var ExtendLevelGhostOpenDay = []int{1,4,0,}






