package item

const (
	ITEM_BOX_CONTENT_MODE_DIRECT      = 0 //直接获得
	ITEM_BOX_CONTENT_MODE_RANDOM_NUM  = 1 //随机数量
	ITEM_BOX_CONTENT_MODE_MAY_GET     = 2 //概率获得
	ITEM_BOX_CONTENT_MODE_RANDOM_ITEM = 3 //随机物品

	ITEM_BOX_CONTENT_TYPE_COIN  = 0 //铜钱
	ITEM_BOX_CONTENT_TYPE_INGOT = 1 //元宝
	ITEM_BOX_CONTENT_TYPE_ITEM  = 2 //物品
	ITEM_BOX_CONTENT_TYPE_EXP   = 3 //主角经验

	ITEM_BOX_CONTENT_TYPE_HEART      = 4 //爱心
	ITEM_BOX_CONTENT_TYPE_PHYSICAL   = 5 //体力
	ITEM_BOX_CONTENT_TYPE_GHOST      = 6 //魂侍
	ITEM_BOX_CONTENT_TYPE_SWORD_SOUL = 7 //剑心
	ITEM_BOX_CONTENT_TYPE_PET        = 8 //灵宠
	ITEM_BOX_CONTENT_TYPE_FRAGMENT   = 9 //剑心碎片

	EXCHANGE_GHOST_CRYSTAL_ONE = 0 //兑换魂侍水晶数量1个
	EXCHANGE_GHOST_CRYSTAL_ALL = 1 //兑换魂侍水晶数量所有
)
